  import './new-var-target.js';
  import './new-core.js';
  import './hand-over.js';
  import './finish.js';
  import './is.js';
  import './synth-names.js';
  import './head.js';
  import './strict.js';
  import './ref.js';
  import './has.js';
  import './enter-exit.js';
  import './can.js';
  import './new-decl.js';
  import './inside.js';
  import './global.js';
  import './spawn.js';
  import {Scope, cls} from './ctor.js';
  export default Scope;
  export {cls};
