  import './src/Scope/new-var-target.js';
  import './src/Scope/new-core.js';
  import './src/Scope/hand-over.js';
  import './src/Scope/finish.js';
  import './src/Scope/is.js';
  import './src/Scope/synth-names.js';
  import './src/Scope/head.js';
  import './src/Scope/strict.js';
  import './src/Scope/ref.js';
  import './src/Scope/has.js';
  import './src/Scope/enter-exit.js';
  import './src/Scope/can.js';
  import './src/Scope/new-decl.js';
  import './src/Scope/inside.js';
  import './src/Scope/global.js';
  import './src/Scope/spawn.js';
  import {Scope, cls} from './ctor.js';
  export default Scope;
  export {cls};
