  import './core.js';
  import './new-core.js';
  import './hand-over.js';
  import './sp.js';
  import './synth-names.js';
  import './strict.js';
  import './can.js';
  import './args-unique.js';
  import {FunScope, cls} from './cls.js';
  export default FunScope;
  export {cls};
